name: Docker CI
on:
  push:
    branches: [ "main" ]

jobs:
  Dokcer-Login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Nginx Image build
        run: |
          docker build -t choigunwoo/source-file:nginx ./Nginx
          docker push choigunwoo/source-file:nginx