name: Docker CI
on:
  push:
    branches: [ "main", "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  Docker-Login:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          # registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

  Image-Build:
    needs: Docker-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Back Image Build
        run: docker build -t choigunwoo/source-file:${{ env.IMAGE_NAME }} .
  
  Image-push:
    needs: Image-Build
    runs-on: ubuntu-22.04
    steps:
      # Error: Process completed with exit code 1.
      - name: Docker Hub push
        uses: docker/build-push-action@v6
        run: docker push choigunwoo/source-file:backend