name: Docker CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  Dokcer-Login:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Front Image Build
        run: docker build -t choigunwoo/source-file:frontend ./Frontend
      
      - name: Docker Hub push
        run: docker push choigunwoo/source-file:frontend