name: Docker CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  Dokcer-Login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  Docker-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository root for debugging
        run: |
          ls -R

      - name: Front Image Build
        run: |
          docker build -t choigunwoo/source-file:frontend ./project-private-files/Frontend
          docker push choigunwoo/source-file:frontend

      - name: Back Image Build
        run: |
          docker build -t choigunwoo/source-file:backend ./project-private-files/Backend
          docker push choigunwoo/source-file:backend

      - name: MySQL Image Build
        run: |
          docker build -t choigunwoo/source-file:mysql ./project-private-files/MySQL
          docker push choigunwoo/source-file:mysql

      - name: Redis Image Build
        run: |
          docker build -t choigunwoo/source-file:redis ./project-private-files/Redis
          docker push choigunwoo/source-file:redis

      - name: Nginx Image Build
        run: |
          docker build -t choigunwoo/source-file:nginx ./project-private-files/Nginx
          docker push choigunwoo/source-file:nginx