name: Docker CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  # App-build:
  #   - name: Front
  #     uses:
  #     path:

  #   - name: Back
  #     uses:
  #     path:

  Dokcer-Login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}